gridsuite/gateway

src/main/java/org/gridsuite/gateway/GatewayConfig.java

Signed-off-by: ChamseddineBhd <chamseddine.benhamed@ensi-uma.tn>

Add allowed-issuers property source from config folder

---

src/main/java/org/gridsuite/gateway/TokenValidatorGlobalPreFilter.java

Signed-off-by: ChamseddineBhd <chamseddine.benhamed@ensi-uma.tn>

Set log level to info

---

src/main/java/org/gridsuite/gateway/TokenValidatorGlobalPreFilter.java

Signed-off-by: ChamseddineBhd <chamseddine.benhamed@ensi-uma.tn>

Check Authorization header's value

---

src/main/java/org/gridsuite/gateway/GatewayConfig.java
src/main/resources/application.yml
src/test/java/org/gridsuite/gateway/TokenValidationTest.java

Signed-off-by: chamseddine <chamseddine.benhamed@ensi-uma.tn>

Add merge notification server route

---

src/main/java/org/gridsuite/gateway/GatewayConfig.java

Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@rte-france.com>

Fix merge notification routing

---

src/main/java/org/gridsuite/gateway/TokenValidatorGlobalPreFilter.java
src/test/java/org/gridsuite/gateway/TokenValidationTest.java

check the subject in header before rerouting

---

src/main/java/org/gridsuite/gateway/TokenValidatorGlobalPreFilter.java
src/test/java/org/gridsuite/gateway/TokenValidationTest.java

add issuer in requests before redirecting

---

src/main/java/org/gridsuite/gateway/GatewayConfig.java
src/main/resources/application.yml
src/test/java/org/gridsuite/gateway/TokenValidationTest.java

Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@rte-france.com>

Add merge orchestrator

---

src/test/java/org/gridsuite/gateway/TokenValidationTest.java

if your mess up the /notify url (replace with xxx), previously you only get in the logs
io.netty.handler.codec.http.websocketx.WebSocketHandshakeException: Invalid handshake response getStatus: 404 Not Found
but the test succeeds.
Now you get 
```
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.603 s <<< FAILURE! - in org.gridsuite.gateway.TokenValidationTest
[ERROR] gatewayTest  Time elapsed: 1.752 s  <<< FAILURE!
java.lang.AssertionError: websocket client was closed but should remain open
at org.gridsuite.gateway.TokenValidationTest.testWebsocket(TokenValidationTest.java:168)
at org.gridsuite.gateway.TokenValidationTest.gatewayTest(TokenValidationTest.java:241)
```

Improve test to fail if ws connection doesn't establish

---

src/main/java/org/gridsuite/gateway/TokenValidatorGlobalPreFilter.java
src/test/java/org/gridsuite/gateway/TokenValidationTest.java

remove issuer

---

src/main/java/org/gridsuite/gateway/GatewayConfig.java
src/main/resources/application.yml
src/test/java/org/gridsuite/gateway/TokenValidationTest.java

Signed-off-by: chamseddine <chamseddine.benhamed@ensi-uma.tn>

Add actions-server 

---

src/main/resources/application.yml

Signed-off-by: Jon Harper <jon.harper87@gmail.com>

Add hostname to /actuator/info to troubleshoot prod problem

---

src/main/java/org/gridsuite/gateway/TokenValidatorGlobalPreFilter.java

Signed-off-by: Jon Harper <jon.harper87@gmail.com>

Fix apache routing bug after websocket handshake rejection by force closing the tcp connection

---

src/main/java/org/gridsuite/gateway/GatewayConfig.java
src/main/resources/application.yml
src/test/java/org/gridsuite/gateway/TokenValidationTest.java

add config-ui and config-ui-notif

---

pom.xml

dependencies V5

---

src/main/java/org/gridsuite/gateway/GatewayConfig.java
src/main/resources/application.yml
src/test/java/org/gridsuite/gateway/TokenValidationTest.java

https://dev.azure.com/GridSuite/MVP/_sprints/backlog/MVP%20Team/MVP/Sprint%2027?workitem=460

Add cgmes-boundary-server

---

src/main/java/org/gridsuite/gateway/GatewayConfig.java

Fix dynamic mapping getter to properly access the server

Fix DynamicMapperServerBaseUri getter

---

pom.xml

springboot 2.4.7

---

src/main/java/org/gridsuite/gateway/GatewayConfig.java
src/main/resources/allowed-issuers.yml
src/main/resources/application.yml
src/test/java/org/gridsuite/gateway/TokenValidationTest.java

Signed-off-by: chamseddine <chamseddine.benhamed@ensi-uma.tn>

add directory-notification-server route

---

src/main/java/org/gridsuite/gateway/endpoints/StudyServer.java
src/test/java/org/gridsuite/gateway/ElementAccessControlTest.java

Signed-off-by: LE SAULNIER Kevin <kevin.lesaulnier@rte-france.com>

New allowed route to get default provider defined in study server

---

src/main/resources/config/application.yaml

Signed-off-by: Abdelsalem <abdelsalem.hedhili@rte-france.com>

increase_max_url_length

---

src/main/java/org/gridsuite/gateway/GatewayConfig.java
src/main/java/org/gridsuite/gateway/ServiceURIsConfig.java
src/main/java/org/gridsuite/gateway/endpoints/NetworkConversionServer.java
src/main/resources/application-local.yml

Signed-off-by: LE SAULNIER Kevin <kevin.lesaulnier@rte-france.com>

Network-conversion-server can now be requested through the gateway

---

src/main/java/org/gridsuite/gateway/GatewayService.java
src/main/java/org/gridsuite/gateway/filters/TokenValidatorGlobalPreFilter.java
src/test/java/org/gridsuite/gateway/TokenValidationTest.java

- add cache to public keys
- add retry after fail on validation from cache data

add cache to jwkset (public keys) and jwk uri

---

src/main/java/org/gridsuite/gateway/GatewayConfig.java
src/main/java/org/gridsuite/gateway/ServiceURIsConfig.java
src/main/java/org/gridsuite/gateway/endpoints/UserAdminServer.java
src/main/java/org/gridsuite/gateway/filters/TokenValidatorGlobalPreFilter.java
src/main/java/org/gridsuite/gateway/filters/UserAdminControlGlobalPreFilter.java
src/main/java/org/gridsuite/gateway/services/UserAdminService.java
src/main/resources/application-local.yml
src/test/java/org/gridsuite/gateway/ElementAccessControlTest.java
src/test/java/org/gridsuite/gateway/TokenValidationTest.java
src/test/java/org/gridsuite/gateway/UserAdminControlTest.java

Signed-off-by: Etienne Homer <etiennehomer@gmail.com>

use_user_admin_server

---

src/main/java/org/gridsuite/gateway/endpoints/UserAdminServer.java

Signed-off-by: Etienne Homer <etiennehomer@gmail.com>

fix user admin 

---

src/main/java/org/gridsuite/gateway/ServiceURIsConfig.java
src/main/java/org/gridsuite/gateway/endpoints/StudyNotificationServer.java
src/main/resources/application-local.yml
src/test/java/org/gridsuite/gateway/TokenValidationTest.java

Signed-off-by: Florent MILLOT <florent.millot@rte-france.com>

Rename notification-server into study-notification-server

---

src/main/java/org/gridsuite/gateway/GatewayConfig.java
src/main/java/org/gridsuite/gateway/ServiceURIsConfig.java
src/main/java/org/gridsuite/gateway/endpoints/LoadFlowServer.java
src/main/java/org/gridsuite/gateway/endpoints/SecurityAnalysisServer.java
src/main/java/org/gridsuite/gateway/endpoints/StudyServer.java
src/main/resources/application-local.yml
src/test/java/org/gridsuite/gateway/ElementAccessControlTest.java

Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@rte-france.com>

Add loadflow an security analysis server to gateway

---

pom.xml
src/main/java/org/gridsuite/gateway/endpoints/EndPointElementServer.java
src/main/java/org/gridsuite/gateway/filters/TokenValidatorGlobalPreFilter.java
src/main/java/org/gridsuite/gateway/services/UserAdminService.java
src/test/java/org/gridsuite/gateway/ElementAccessControlTest.java
src/test/java/org/gridsuite/gateway/TokenValidationTest.java

Need powsybl/powsybl-parent#65

Migrate tests to JUnit5
